In [4]:
import numpy as np

array([1, 2, 3, 4])

In [5]:
my_list1 = [1,2,3,4]

array([1, 2, 3, 4])

In [6]:
my_array1 = np.array(my_list1)
my_array1

array([1, 2, 3, 4])

In [7]:
my_list2 = [12,54,56,7]

In [9]:
my_lists = [my_list1, my_list2]

In [10]:
my_array2 = np.array(my_lists)

In [12]:
my_array2

array([[ 1,  2,  3,  4],
       [12, 54, 56,  7]])

In [15]:
my_array2.shape

(2, 4)

In [17]:
my_array2.dtype

dtype('int32')

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [29]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])