In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [7]:
# normal random distribution of some random numbers
a = np.random.randn(10)
a

array([-0.29539833,  2.82384531, -0.75772375,  0.5682969 , -0.17529634,
        0.18151046, -1.38811335,  2.20928821, -0.15737508,  0.00714601])

In [8]:
b = np.random.randn(10)
b

array([ 1.02775009, -0.54231367,  0.28822737, -0.71859632,  1.70525324,
       -0.19979412,  0.91942711, -0.71010351,  0.35868505,  0.09072946])

In [10]:
# binary functions

# adding values of arrays
np.add(a,b)

array([ 0.73235177,  2.28153164, -0.46949637, -0.15029942,  1.5299569 ,
       -0.01828365, -0.46868624,  1.49918471,  0.20130997,  0.09787546])

In [11]:
# max between 2 arrays
np.maximum(a,b)

array([1.02775009, 2.82384531, 0.28822737, 0.5682969 , 1.70525324,
       0.18151046, 0.91942711, 2.20928821, 0.35868505, 0.09072946])

In [12]:
import webbrowser
webbrowser.open('https://www.google.com/')

True