In [2]:
import numpy as np

In [5]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [10]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [13]:
# normal random distribution of some random numbers
a = np.random.randn(10)
a

array([-0.36089923, -0.14828954,  0.08648262,  0.24369191,  0.16970513,
       -2.71069698, -0.58710846, -0.00284486, -0.51522318, -0.98194397])

In [15]:
b = np.random.randn(10)
b

array([-0.60855073,  0.33357149,  2.30906992,  0.13612084, -0.98616335,
        1.86449371, -2.17087685, -0.06257338,  0.76498455,  1.7114685 ])

In [21]:
# binary functions

# adding values of arrays
np.add(a,b)

array([-0.96944996,  0.18528195,  2.39555254,  0.37981276, -0.81645822,
       -0.84620327, -2.75798531, -0.06541824,  0.24976138,  0.72952453])

In [23]:
# max between 2 arrays
np.maximum(a,b)

array([-0.36089923,  0.33357149,  2.30906992,  0.24369191,  0.16970513,
        1.86449371, -0.58710846, -0.00284486,  0.76498455,  1.7114685 ])

In [25]:
import webbrowser
webbrowser.open('https://www.google.com/')

True