In [1]:
import numpy as np
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [2]:
# saving a single arr into a file, file output is in the same directory
np.save('myarr',arr)

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr1 = np.load('myarr.npy')
arr1

array([0, 1, 2, 3, 4])

In [6]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4])

In [7]:
# saving multiple arrays
np.savez('ziparray.npz', x=arr1, y=arr2)

In [8]:
archive_arr = np.load('ziparray.npz')

In [9]:
archive_arr['x']

array([0, 1, 2, 3, 4])

In [10]:
archive_arr['y']

array([0, 1, 2, 3, 4])

In [20]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# save as txt file
np.savetxt('mytextarray.txt',arr,delimiter=',')

In [23]:
# load txt file
arr = np.loadtxt('mytextarray.txt', delimiter=',')
arr

array([[1., 2., 3.],
       [4., 5., 6.]])