In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
dframe = DataFrame(np.arange(16).reshape(4,4))
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [16]:
# randomize the order between 0-3
blender = np.random.permutation(4)
blender

array([1, 0, 2, 3])

In [21]:
# rearrange/permutate the order of dframe indexes based on blender's
dframe.take(blender)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15

In [23]:
# permutation with values replacement
box = np.array([1,2,3])
# create an array with random int going from 0 (low), to length of box(high) as values, size is # of times we pick a random value from box[]
shaker = np.random.randint(0,len(box),size=10)
shaker

array([0, 2, 0, 2, 1, 2, 1, 2, 0, 1])

In [24]:
# take an index value from box[] using shaker 
hand_grabs = box.take(shaker)
hand_grabs

array([1, 3, 1, 3, 2, 3, 2, 3, 1, 2])