In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [4]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# concatenate along the x axis in np
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
# concatenate along the y axis in np
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
ser1 = Series([0,1,2], index = ['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])

In [15]:
# concatenate in pd, default along the y axis
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [18]:
# pd concatenate and specify the axis, example below is x axis, return NaN when value is missing from either table
# notice concat along x axis returned a DataFrame and not a Series as above example
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [19]:
# adding keys/label to the concat Series, labeling them through a hierachial index
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

# concate using DataFrame

In [20]:
 dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])
 dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])    

In [21]:
# return NaN for key values not in one of the table
# also notice the order of the indexes are not in order
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0  1.884726 -0.480048 -1.286268       NaN
1  1.143598  0.042307  1.336903       NaN
2 -0.310401  1.429759  0.324962       NaN
3 -1.457619  0.696265 -0.452802       NaN
0  1.747210  1.714861       NaN  1.678251
1 -0.987371  0.310272       NaN -0.172742
2 -0.671606  0.856673       NaN  2.820751

In [22]:
# to "ignore" the unordered indexes, use arguement ignore_index=True
pd.concat([dframe1,dframe2], ignore_index=True)

X         Y         Z         Q
0  1.884726 -0.480048 -1.286268       NaN
1  1.143598  0.042307  1.336903       NaN
2 -0.310401  1.429759  0.324962       NaN
3 -1.457619  0.696265 -0.452802       NaN
4  1.747210  1.714861       NaN  1.678251
5 -0.987371  0.310272       NaN -0.172742
6 -0.671606  0.856673       NaN  2.820751

In [ ]:
#  more information on concatenate
url = 'https://pandas.pydata.org/docs/reference/api/pandas.concat.html'